### ISSUE TITLE
Mouse gesture issues

### ISSUE THREAD

**Issue by mpenguin** [marklieberman/foxygestures#20]
Hi! I saw your post on reddit.com/r/firefox about moving over to Foxy Gestures from FireGestures. I used FireGestures (and am using Foxy Gestures) mostly for the mouse gestures, but I've noticed a few issues.

I have right-click+scroll up set to Open New Tab. I've noticed that most of the time, it will open a new tab, but it also opens the context menu on the new tab. This means that if I start typing an address/search right away, it triggers something in the context menu, and I end up getting a random page or changing settings.

My right-click+scroll down is set to Reload Page. This works fine, but I've noticed that many times if I simply scroll down a webpage (without mouse input), it will reload. I'm not sure why this is happening without mouse input.

Is there someway to save an input log to attach to this issue?

Thanks! I really appreciate you creating a WebExtension for this purpose!

**Comment by marklieberman** [comment]
The new tab situation is a limitation of web extensions. WE cannot inject scripts into about:newtab so I have no way to prevent the context menu.

I am not able to reproduce the second issue. Does this issue only occur on one or two specific websites? If the website is creating a synthetic right click it might trigger it. If you tell me a site to test on, it would help.

There is no log, but if you see any errors in the browser console (Ctrl+Shift+J) from mouseEvents.js it would be related. Usually an error would break it though, not trigger a gesture.

**Comment by mpenguin** [comment]
As for the second issue (reload on scroll down with no mouse input), I've had it happen on Gmail, Youtube, Reddit, and a few others. I'll start logging the address of each website that it happens on and try paying attention to mouseEvents.js.

For the first issue, I've noticed that SmartUp Gestures never gives me a context menu, but they also have a Google Search page (not the FireFox New Tab page) for opening a new tab via mouse gesture. Is this different from injecting a script into about:newtab? I'm not a programmer, so I really don't understand the code differences.

**Comment by marklieberman** [comment]
You can change the default address for the new tab commands in Other Preferences. The addresses that start with about: are internal to the browser and and web extensions don't have access to to them.

The context menu might show up when you change tab or reload with wheel gestures. I had a bit of code that was supposed to prevent that but it was causing problems in another case so I removed it. I need to work on a different solution.

**Comment by marklieberman** [comment]
@mpenguin I think I triggered the issue you are having. While doing my normal surfing, somehow while opening a tab I managed to get the gesture state "stuck on". I was not able to repeat it even with many attempts so I think it has to do with a timing issue when the mouse gesture script is being loaded. I'll look into it further.

**Comment by marklieberman** [comment]
@mpenguin Can you try the latest release (1.0.7) and let me know if you are still experiencing issues with the wheel gestures? Thanks.

**Comment by mpenguin** [comment]
Just installed 1.0.7. I'll watch it over the next few days to see if the issue occurs again. Thanks!

**Comment by mpenguin** [comment]
Definitely still getting the same issue, although it seems to be limited to Youtube and Facebook. For some reason, it often happens just after I reload the page: I'll hit the "Home" button on Facebook and allow it to reload; scrolling down is then interpreted as a rocker gesture (right mouse btn + scroll down = reload) and the page is reloaded, sometimes several times (as if the right mouse button is being held down). Very curious.

I'm using Firefox. How can I view the MouseEvents.js? Or what should I be paying attention to in the Developer Tools to figure out what's going on?

**Comment by marklieberman** [comment]
If you are not seeing any errors in the browser console related to Foxy Gestures scripts that it gets event harder to debug. Lets start with some basic questions:

1) What edition of Firefox are you running? Release, Developer or Nightly?
2) What other addons do you have installed?
3) Are you running any userscripts? (the Grease/Tamper/Violentmonkey family of addons)
4) Is there anything special about your mouse? Are you using software like Logitech SetPoint?
5) Is there any accessibility settings related to mice enabled in Windows?

Also, in 1.0.7 I added a backup settings function. Would you mind posting your settings?

**Comment by marklieberman** [comment]
I think I found a possible cause of the problem. Its like this: the gesture state in each tab is independent because of web extensions reasons. Its normally not a problem, except when you have something like a wheel gesture that changes the active tab. (e.g.: Next Tab, Previous Tab). I want it so that if you keep scrolling the wheel, it keeps switching tabs. The problem is that when the next tab activates it doesn't know that a gesture is in progress. The solution I came up with is to clone the gesture state and send it to the next tab before activating it. Anyway, I found a racy condition in the gesture state cloning logic that cloned the wrong values that could cause the gesture to get "stuck on."

I re-wrote the gesture state cloning logic and published a beta version 1.0.8beta1 to the development channel. Would you mind giving it a try? https://addons.mozilla.org/en-US/firefox/addon/foxy-gestures/versions/beta

**Comment by marklieberman** [comment]
@mpenguin I just published 1.0.8beta4 which I am very confident will fix the issue. Please try it out for me, thanks. I was finally able to reproduce the issue consistently.

**Comment by mpenguin** [comment]
Hi, been busy the past week or so. I've been using 1.0.8b4 for about 24 hours and haven't noticed the issue popping up. I may have discovered another issue, though, but I'll leave that for now. A few more days of testing/browsing and we'll see.

Thanks for your hard work!

**Comment by mpenguin** [comment]
Sorry for the late notice; been busy again.

The issue is definitely still present and, in some ways, perhaps even worse than before. I've noticed it particularly on Facebook, but it seems to be triggered when I switch between tabs or from one program back to Firefox. Again, I'm not really sure where to look to get a more technical readout on what is happening, but I've kindof gotten into the habit of using ctrl-t to open new tabs and right-clicking on pages to "disable" the sticking mouseevent.

**Comment by marklieberman** [comment]
Which gestures have you bound to the wheel? I definitely fixed the sticky gesture thing for Next Tab/Previous Tab. There isn't a technical readout to be had unless you start stepping through code with the debugger.

**Comment by mpenguin** [comment]
I have Right MsBtn + Scroll Up set to 'Open New Tab' and Right MsBtn + Scroll Down set to 'Reload Page'.

So this often results in me clicking to Facebook or Reddit, scrolling down, and triggering a reload. Or triggering several new windows to open up.

**Comment by marklieberman** [comment]
I believe its a similar situation to the new/prev tab command in that the tab is losing focus while the wheel gesture is active. I'll try to fix this tonight and have another beta. Thank you for putting up with it until now.

**Comment by marklieberman** [comment]
@mpenguin To reproduce your issue do the following:
1) Use the wheel gesture to open a new tab. The new tab should get focus.
2) Immediately go back to the first tab and scroll the mouse wheel.

This is fixed in beta6 which is now on AMO.

I need to promote a build to AMO this week because I need the new version be reviewed before FF 56 goes to release at the end of the month. I know you're busy but please get back to me quickly if possible. Thank you.

**Comment by mpenguin** [comment]
I've installed Beta6 and can confirm that the issue—at least in the situation you describe—is fixed. Thanks! I'll keep an eye out to see if it happens in any other situations (switching from different programs, for example).

Great work!
